### ISSUE TITLE
Renders nothing when having single root element

### ISSUE THREAD

**Issue by dundalek** [brigand/react-safe-html#5]
Nothing gets rendered when having markup with single root element like `<p>does not render</p>`.

Adding an extra element makes it work: `<p>this will get</p><p>rendered</p>`. As a workaround adding trailing space helps too.

**Comment by brigand** [comment]
Thanks for the report. I can't figure out what's wrong, so I just used the space hack for now. Any ideas?

**Comment by brigand** [comment]
edit: oops wrong issue
