### ISSUE TITLE
Invalid DOM property `frameborder`. Did you mean `frameBorder`

### ISSUE THREAD

**Issue by jozefcipa** [brigand/react-safe-html#7]
When _react-safe-html_ renders iframe it causes Invalid DOM property `frameborder`. Did you mean `frameBorder`? error. But when I use *frameBorder* in component it **DOESN'T** affect rendered iframe's border. However `frameborder` does (but it throws this warning).

Check out https://github.com/facebook/react/issues/12494

**Comment by brigand** [comment]
Hello! I'm not sure why you closed this, but try the approach in the "Adding/replacing elements" section of the readme, where it renames an html attribute to a react prop.

From the readme:

```js
components.input = ReactSafeHtml.components.createSimpleElement('input', {
  value: true,
  placeholder: true,
  'tab-index': (index) => ['tabIndex', index],
});
```

My guess at what'd work:

```js
components.iframe = ReactSafeHtml.components.createSimpleElement('iframe', {
  'frameborder': (value) => ['frameBorder', value],
});
```

Or maybe `'frameborder': (value) => ['frameBorder', parseInt(value, 10)]`, and then the rest of the properties you want to support.

**Comment by jozefcipa** [comment]
Hello, yes that was exactly the problem. I was displaying HTML content from CKEditor and there was set “frameborder” in iframe internally. I changed this and now it’s working great. 
I didn’t notice code you have posted here but that’s exactly what would help. Anyway I closed the issue as soon as I realized that.

**Comment by brigand** [comment]
Cool. Btw, issues are a great place for people to find solutions to problems, so if you solve an issue, it's very helpful to post your solution, so the next person that ends up on this page can see it.
